@echo off
REM OpenAPV Multi-Mip Test Runner
REM Runs multi-mip decoder tests and generates PNG visualizations

REM Set paths as variables
set DECODER_EXE=..\build\Release\decoder_test.exe
set MEDIA_4K=media\koala_tiled\koala_tiled_0000.apv1

echo ========================================
echo OpenAPV Multi-Mip Test Runner
echo ========================================
echo.

REM Check if test media exists
if not exist %MEDIA_4K% (
    echo ERROR: 4K test media not found!
    echo Expected: %MEDIA_4K%
    exit /b 1
)

REM Create output directory if it doesn't exist
if not exist output mkdir output

REM Clean previous test outputs
echo Cleaning previous test outputs...
del /Q output\*.raw 2>nul
del /Q output\*.y4m 2>nul
del /Q output\*.png 2>nul
echo.

REM Build the tests
echo Building decoder tests...
cmake --build ..\build --config Release --target decoder_test
if errorlevel 1 (
    echo ERROR: Build failed!
    exit /b 1
)
echo.

REM Run Multi-Mip decoder tests
echo ========================================
echo Running Multi-Mip decoder tests...
echo ========================================

REM Core multi-mip functionality tests
echo Running core multi-mip tests...
%DECODER_EXE% %MEDIA_4K% multimip_single_center
%DECODER_EXE% %MEDIA_4K% multimip_2x2_blocks
%DECODER_EXE% %MEDIA_4K% multimip_sparse

REM Error handling test (missing mip)
echo Running error handling test...
%DECODER_EXE% %MEDIA_4K% multi_all_mip9

REM Performance comparison test
echo Running performance comparison test...
%DECODER_EXE% %MEDIA_4K% multimip_performance_comparison

REM Invalid test (all invalid mips)
echo Running invalid test...
%DECODER_EXE% %MEDIA_4K% invalid_test

REM Check for test failures
if errorlevel 1 (
    echo ERROR: One or more multi-mip tests failed!
    exit /b 1
)
echo.

REM Convert all Y4M files to PNG for visual inspection
echo ========================================
echo Converting Y4M files to PNG images...
echo ========================================
setlocal enabledelayedexpansion
set count=0
for %%f in (output\*.y4m) do (
    set /a count+=1
    echo [!count!] Converting %%~nf.y4m to PNG...
    python src\convert_y4m_to_png.py "%%f"
    if errorlevel 1 (
        echo WARNING: Failed to convert %%f - trying alternative method...
        python src\convert_tile_to_png.py "%%f"
    )
)
echo Total Y4M files converted: %count%
endlocal
echo.

REM Generate summary
echo ========================================
echo Multi-Mip Test Summary
echo ========================================
echo.

echo Generated outputs:
setlocal enabledelayedexpansion
for %%e in (y4m png) do (
    set count=0
    for %%f in (output\*.%%e) do set /a count+=1
    if !count! gtr 0 echo   %%e files: !count!
)
endlocal
echo.

REM Display file list by mip level
echo Files generated by mip level:
echo -----------------------------
for %%m in (0 1 2 3 4 5 6 7 8 9) do (
    echo Mip %%m files:
    dir /B output\*mip%%m*.y4m 2>nul
    if errorlevel 1 echo   (No mip %%m files found)
)
echo.

echo ========================================
echo All Multi-Mip tests completed successfully!
echo ========================================
echo.
echo To view results:
echo   explorer output
echo.
echo Multi-mip test results show:
echo 1. Single center tile decoded from multiple mip levels
echo 2. 2x2 tile blocks decoded from multiple mip levels
echo 3. Sparse tiles decoded from multiple mip levels
echo 4. Error handling for non-existent mip levels
echo 5. Performance comparison between multi-mip and individual calls
echo.